# Dockerfile for Building (and Testing) GlusterFS

# Build using `docker build -t glusterfs:latest .` or `./run-tests-in-docker.sh`

FROM centos:7

RUN yum install -y git autoconf automake libtool make epel-release \
    && yum install -y flex bison \
        libacl-devel userspace-rcu-devel openssl-devel libxml2-devel libtirpc-devel \
        sqlite-devel python-devel fuse-devel \
        librdmacm-devel libibverbs-devel readline-devel lvm2-devel libaio-devel \
        dbench nfs-utils yajl-devel xfsprogs e2fsprogs attr sysvinit-tools bc \
        file which psmisc

COPY . /opt/glusterfs/src

WORKDIR /opt/glusterfs/src

RUN ./autogen.sh \
    && ./configure

# FIXME: env.rc is generated by ./configure but then deleted by make clean...
RUN mv tests/env.rc /opt/glusterfs/env.rc \
    && make clean \
    && cp /opt/glusterfs/env.rc tests/env.rc
RUN make -j
RUN make -j install

VOLUME /d/

ENTRYPOINT /opt/glusterfs/src/tests/docker/entrypoint.sh
